name: spot
base: core20 # the base snap is the execution environment for this snap
adopt-info: spot
summary: Gtk/Rust native Spotify client for the GNOME desktop.
description: |
  Gtk/Rust native Spotify client for the GNOME desktop.

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

parts:
  spot:
    plugin: meson
    source: https://github.com/xou816/spot.git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tag)"
    build-packages:
      - build-essential
      - pkg-config
      - meson
      - cargo
      - libssl-dev
      - libglib2.0-dev-bin
      - libgtk-3-dev
      - libasound2-dev
      - libpulse-dev
    meson-parameters: [--prefix=/usr, -Dbuildtype=release, -Doffline=false]
    build-environment:
      - PATH: $HOME/.cargo/bin:$PATH
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/pkgconfig:$PKG_CONFIG_PATH
    override-build: |
      #export DESTDIR=$SNAPCRAFT_PART_INSTALL
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      . $HOME/.cargo/env
      rustup toolchain install nightly
      rustup default nightly
      snapcraftctl build

layout:
  /usr/share/spot/spot.gresource:
    symlink: $SNAP/usr/share/spot/spot.gresource

slots:
  spot:
    interface: dbus
    bus: session
    name: dev.alextren.Spot
  spot-mpris:
    interface: mpris
    name: Spot

apps:
  spot:
    command: usr/bin/spot
    extensions: [gnome-3-38]
    common-id: dev.alextren.Spot
    plugs:
      - audio-playback
      - network
      - x11
      - opengl
      - desktop
      - desktop-legacy
      - password-manager-service
