name: spot
base: core24
version: 0.4.1
summary: Gtk/Rust native Spotify client for the GNOME desktop.
description: |
  Gtk/Rust native Spotify client for the GNOME desktop.

platforms:
  x86_64-linux-gnu:
    build-for: amd64
    build-on: amd64
  aarch64-linux-gnu:
    build-for: arm64
    build-on: arm64

grade: stable
confinement: strict

parts:
  spot:
    plugin: meson
    source: https://github.com/xou816/spot.git
    build-packages:
      - build-essential
      - pkg-config
      - curl
      - meson
      - cargo
      - libssl-dev
      - libglib2.0-dev-bin
      - libgtk-4-dev
      - libadwaita-1-dev
      - libasound2-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgirepository1.0-dev
      - gobject-introspection
    meson-parameters: [--prefix=/usr, -Dbuildtype=release, -Doffline=false]
    build-environment:
      - PATH: $HOME/.cargo/bin:$PATH
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/pkgconfig:$PKG_CONFIG_PATH
    override-build: |
      #export DESTDIR=$CRAFT_PART_INSTALL
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      . $HOME/.cargo/env
      rustup toolchain install stable
      rustup default stable
      craftctl default

layout:
  /usr/share/spot/spot.gresource:
    symlink: $SNAP/usr/share/spot/spot.gresource

slots:
  spot:
    interface: dbus
    bus: session
    name: dev.alextren.Spot
  spot-mpris:
    interface: mpris
    name: Spot

apps:
  spot:
    command: usr/bin/spot
    extensions: [gnome]
    common-id: dev.alextren.Spot
    plugs:
      - audio-playback
      - network
      - x11
      - opengl
      - desktop
      - desktop-legacy
      - password-manager-service
