name: spot
base: core22 # the base snap is the execution environment for this snap
adopt-info: spot
summary: Gtk/Rust native Spotify client for the GNOME desktop.
description: |
  Gtk/Rust native Spotify client for the GNOME desktop.

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

parts:
  spot:
    plugin: meson
    source: https://github.com/xou816/spot.git
    #source-tag: '0.1.12'
    override-pull: |
      set -eu
      craftctl default
      last_rev="$(git rev-list --tags --max-count=1)"
      last_committed_tag="$(git describe --tags $last_rev)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      craftctl set version=$(git -C ../src describe --tags)
    build-packages:
      - build-essential
      - pkg-config
      - curl
      - meson
      - cargo
      - libssl-dev
      - libglib2.0-dev-bin
      - libgtk-3-dev
      - libasound2-dev
      - libpulse-dev
    meson-parameters: [--prefix=/usr, -Dbuildtype=release, -Doffline=false]
    build-environment:
      - PATH: $HOME/.cargo/bin:$PATH
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/usr/lib/pkgconfig:$PKG_CONFIG_PATH
    override-build: |
      #export DESTDIR=$SNAPCRAFT_PART_INSTALL
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      . $HOME/.cargo/env
      rustup toolchain install stable
      rustup default stable
      craftctl default

layout:
  /usr/share/spot/spot.gresource:
    symlink: $SNAP/usr/share/spot/spot.gresource

slots:
  spot:
    interface: dbus
    bus: session
    name: dev.alextren.Spot
  spot-mpris:
    interface: mpris
    name: Spot

apps:
  spot:
    command: usr/bin/spot
    extensions: [gnome]
    common-id: dev.alextren.Spot
    plugs:
      - audio-playback
      - network
      - x11
      - opengl
      - desktop
      - desktop-legacy
      - password-manager-service
