name: build-test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  snap:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: Build failed show log
      if: ${{ failure() }}
      run: cat /home/runner/.local/state/snapcraft/log/snapcraft*.log
    - uses: actions/upload-artifact@v2
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
